"""Hatchling build hook — stamp _build.py at wheel/sdist/editable install time."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class StampBuildHook(BuildHookInterface):
    def initialize(self, version: str, build_data: dict) -> None:
        build_id = datetime.now().strftime("%Y%m%d%H%M%S")
        build_file = Path(self.root) / "src" / "construct" / "_build.py"
        build_file.write_text(
            '"""Build stamp — regenerated by scripts/stamp_build.py and hatch build hooks."""\n\n'
            f'__build__ = "{build_id}"\n',
            encoding="utf-8",
        )
