"""FIX-02 — the generated ``WORKSPACE.md`` must agree with the spec.

``.construct/model-routing.yaml`` is **deprecated and inert**: nothing reads it,
and it is retained only so ``REQUIRED_PATHS`` workspace-contract checks stay
stable (Phase 14, "deprecate-but-scaffold"). The LLM configuration authority is
``src/construct/llm/config.yaml``.

Four documents record that correctly — ``workspace-contract.md:84``,
``nfrs.md:76``, and ``AGENTS.md`` at both ``:91`` and ``:135``. A fifth writer
was missed in Phase 14: ``_write_workspace_doc`` in
``src/construct/services/init.py`` emits a Support Paths bullet claiming the
file holds live runtime routing guidance. That bullet ships into *every*
workspace ``construct init`` creates, so the copy a user is most likely to read
was the one contradicting the spec.

Design contract
---------------
* **Read the generated bytes, never the source constant.** These tests call
  ``initialize_workspace()`` into a throwaway directory and read the resulting
  ``WORKSPACE.md`` from disk. Asserting against a string literal imported from
  ``init.py`` would let a future edit satisfy the guard by fixing a constant the
  generator does not actually use.
* **Vacuity is the real threat.** Both extractors return the empty string when
  their anchor is missing, so a gutted generator — no ``## Support Paths``
  section, or no model-routing bullet — would make the deprecation assertions
  pass on empty text. ``test_generated_workspace_doc_extraction_is_not_vacuous``
  converts that silence into a loud failure, mirroring
  ``test_catalog_introspection_is_not_vacuous`` in ``test_artifact_catalog.py``.
* **The authority-claim pattern is scoped to the verb that follows the
  filename.** The corrected bullet legitimately names an authority (the llm
  config path), so an unscoped search for authority wording would fail on the
  fixed text. Only ``model-routing.yaml <verb>`` is forbidden.

This guard says nothing about workspace *layout*: ``.construct/model-routing.yaml``
is still scaffolded, still a ``REQUIRED_PATHS`` entry, and still asserted by
``tests/fixtures/expected-workspace-tree.txt``. Only the prose changed.
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest

from construct.services.init import DomainInitInput, initialize_workspace


_WORKSPACE_DOC = "WORKSPACE.md"

# An authority claim made about model-routing.yaml *itself* — the falsehood
# FIX-02 removes. Scoped to the verb immediately following the filename so the
# corrected bullet, which names `src/construct/llm/config.yaml` as the real
# authority, does not trip it.
_AUTHORITY_CLAIM = re.compile(
    r"model-routing\.yaml`?\s+(?:stores|holds|controls|configures|drives|provides)\b",
    re.IGNORECASE,
)


@pytest.fixture(scope="module")
def generated_workspace_doc(tmp_path_factory: pytest.TempPathFactory) -> str:
    """Initialize a throwaway workspace and return its generated ``WORKSPACE.md``.

    ``initialize_workspace`` refuses a target that exists and is non-empty, so
    the workspace goes into a fresh subdirectory of the tmp root.
    """
    root: Path = tmp_path_factory.mktemp("fix02") / "ws"
    workspace = initialize_workspace(
        root,
        DomainInitInput(
            domain_id="example-domain",
            display_name="Example Domain",
            scope="Example scope.",
            taxonomy_seeds=["examples"],
            source_priorities=["peer-reviewed papers"],
            research_seeds=["example seed"],
        ),
    )
    return (workspace / _WORKSPACE_DOC).read_text(encoding="utf-8")


def _support_paths_section(text: str) -> str:
    """Return the ``## Support Paths`` body, or ``""`` if the heading is absent.

    Tolerant of heading order: the section ends at the next ``## `` heading at
    line start, or at end of file.
    """
    match = re.search(
        r"^##[ \t]+Support Paths[ \t]*$(.*?)(?=^##[ \t]|\Z)",
        text,
        re.MULTILINE | re.DOTALL,
    )
    return match.group(1) if match else ""


def _model_routing_row(section: str) -> str:
    """Return the bullet line mentioning ``model-routing.yaml``, or ``""``."""
    for line in section.splitlines():
        stripped = line.strip()
        if stripped.startswith("- ") and "model-routing.yaml" in stripped:
            return stripped
    return ""


def _bullet_lines(section: str) -> list[str]:
    return [line.strip() for line in section.splitlines() if line.strip().startswith("- ")]


def _search_config_row(section: str) -> str:
    """Second structural anchor — the bullet mentioning ``search.yaml``."""
    for line in section.splitlines():
        stripped = line.strip()
        if stripped.startswith("- ") and "search.yaml" in stripped:
            return stripped
    return ""


# ---------------------------------------------------------------------------
# Vacuity meta-guard — MUST run and MUST be able to fail loudly
# ---------------------------------------------------------------------------


def test_generated_workspace_doc_extraction_is_not_vacuous(generated_workspace_doc: str) -> None:
    """Guard the generator's structure AND the two extractors above.

    Without this, deleting the Support Paths section (or just the model-routing
    bullet) would make ``test_model_routing_row_records_deprecation`` pass on the
    empty string — a false green hiding the exact regression this module exists
    to catch.
    """
    text = generated_workspace_doc
    assert text.strip(), f"generated {_WORKSPACE_DOC} is empty — the generator wrote nothing"
    assert "# CONSTRUCT Workspace" in text, (
        f"generated {_WORKSPACE_DOC} lost its '# CONSTRUCT Workspace' title — "
        "_write_workspace_doc no longer produces the expected document"
    )

    for heading in ("## Canonical Paths", "## Derived Paths", "## Support Paths"):
        assert heading in text, (
            f"generated {_WORKSPACE_DOC} is missing the '{heading}' heading — "
            "a gutted generator must fail here, not silently downstream"
        )

    section = _support_paths_section(text)
    assert section.strip(), (
        f"_support_paths_section found no body under '## Support Paths' in generated "
        f"{_WORKSPACE_DOC} — the extractor or the section itself is broken"
    )

    bullets = _bullet_lines(section)
    assert len(bullets) >= 2, (
        f"expected at least 2 bullets in the '## Support Paths' section of generated "
        f"{_WORKSPACE_DOC}, found {len(bullets)}: {bullets!r}"
    )

    row = _model_routing_row(section)
    assert row, (
        f"_model_routing_row found no 'model-routing.yaml' bullet in the '## Support Paths' "
        f"section of generated {_WORKSPACE_DOC} — the row was deleted or the extractor broke"
    )
    assert row.startswith("- "), (
        f"the model-routing row in generated {_WORKSPACE_DOC} is not a markdown bullet: {row!r}"
    )

    second = _search_config_row(section)
    assert second, (
        f"_search_config_row found no 'search.yaml' bullet in the '## Support Paths' section of "
        f"generated {_WORKSPACE_DOC} — the extractor must match by bullet structure, not by one "
        "hardcoded string"
    )
    assert second != row, (
        f"the model-routing and search.yaml anchors resolved to the same line in generated "
        f"{_WORKSPACE_DOC}: {row!r} — the extractor is not discriminating between bullets"
    )


# ---------------------------------------------------------------------------
# The FIX-02 guard: the generated row must record the Phase 14 deprecation
# ---------------------------------------------------------------------------


def test_model_routing_row_records_deprecation(generated_workspace_doc: str) -> None:
    """The generated Support Paths bullet must match the spec in substance.

    Mirrors ``CONSTRUCT-CLAUDE-spec/workspace-contract.md:84`` minus its resolver
    clause — ``WORKSPACE.md`` is a terse orientation file, not a spec.
    """
    section = _support_paths_section(generated_workspace_doc)
    row = _model_routing_row(section)
    # Re-asserted so this test cannot pass vacuously on its own.
    assert row, (
        f"no 'model-routing.yaml' bullet found in the '## Support Paths' section of generated "
        f"{_WORKSPACE_DOC} — see test_generated_workspace_doc_extraction_is_not_vacuous"
    )

    lowered = row.lower()
    assert "deprecated" in lowered, (
        f"the generated {_WORKSPACE_DOC} model-routing bullet does not record the Phase 14 "
        f"deprecation (expected the word 'deprecated'); got: {row!r}. Fix "
        "_write_workspace_doc in src/construct/services/init.py"
    )
    assert "inert" in lowered, (
        f"the generated {_WORKSPACE_DOC} model-routing bullet does not record that the file is "
        f"inert (expected the word 'inert'); got: {row!r}. Fix _write_workspace_doc in "
        "src/construct/services/init.py"
    )

    assert "src/construct/llm/config.yaml" in row, (
        f"the generated {_WORKSPACE_DOC} model-routing bullet does not name the real LLM "
        f"configuration authority 'src/construct/llm/config.yaml'; got: {row!r}. This is the "
        "path recorded by workspace-contract.md:84, nfrs.md:76, and AGENTS.md:135"
    )

    claim = _AUTHORITY_CLAIM.search(row)
    assert claim is None, (
        f"the generated {_WORKSPACE_DOC} model-routing bullet still makes an authority claim for "
        f"model-routing.yaml itself ({claim.group(0)!r} in {row!r}). Nothing reads that file — "
        "describe it as deprecated and inert and point at src/construct/llm/config.yaml"
    )
