#!/usr/bin/env python3
"""Write src/construct/_build.py with the current build stamp."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path


def stamp_build(*, root: Path | None = None, at: datetime | None = None) -> str:
    repo_root = root or Path(__file__).resolve().parents[1]
    build_id = (at or datetime.now()).strftime("%Y%m%d%H%M%S")
    build_file = repo_root / "src" / "construct" / "_build.py"
    build_file.write_text(
        '"""Build stamp — regenerated by scripts/stamp_build.py and hatch build hooks."""\n\n'
        f'__build__ = "{build_id}"\n',
        encoding="utf-8",
    )
    return build_id


if __name__ == "__main__":
    print(stamp_build())
